### ISSUE TITLE
Countries class is clashing with exsiting class/module

### ISSUE THREAD

**Issue by twilliamsark** [taxamo/taxamo-ruby#2]
Is there a version of the gem where your Countries class is namespaced under Taxamo?  It's clashing with gem https://github.com/hexorx/countries.

**Comment by tlipski** [comment]
Sadly not at this moment. But I will keep this issue open so we might propose a solution. 

Fortunately, the library is generated using swagger-codegen, so in extreme case we can afford to have two versions and keep them in sync (although I would prefer to come up with some solution to avoid that).

**Comment by timothee-alby** [comment]
It would be great if the classes could be namespaced. We ran into that exact same issue and it isn't a nice problem to fix.

**Comment by tlipski** [comment]
Apologies for this delay, the 2.0 branch contains namespaced code.
