### ISSUE TITLE
How to deal with double submits?

### ISSUE THREAD

**Issue by bbozo** [taxamo/taxamo-ruby#4]
Hello :)

I'm wondering what to do if for whatever reason a transaction gets submitted twice (repeat after IO error, software bugs, ...), I tried setting `custom_id` but still multiple transactions with different keys get returned when I run this piece of code multiple times:

``` ruby
Taxamo.create_transaction({
  'transaction' => {
    'custom_id' => 'double_custom_id_test',
    'currency_code' => 'USD',
    'buyer_ip' => '127.0.0.1',
    'billing_country_code' => 'IE',
    'force_country_code' => 'FR',
    'transaction_lines' => [
      {
        'amount' => 200,
        'custom_id' => 'line1'
      },
      {
        'amount' => 100,
        'product_type' => 'e-book',
        'custom_id' => 'line2'}
    ]
  }
})
```

If I try to set the `key` explicitly then I get `ValidationError: ["Validation failed: ", "{:transaction {:key disallowed-key}}"]`

**Comment by tlipski** [comment]
Hi, the simplest approach here would be to just ignore the doubled transaction and confirm only one of them using its key.

Taxamo assigns the transaction key, and unfortunately it cannot be user-provided.

**Comment by bbozo** [comment]
A thought, at least one European country (Croatia) will charge taxes for that double transaction because taxes are applied before the invoice is paid for, is there maybe a plan to make the `custom_id` unique constrained?

And maybe a workaround in the meantime? Such as polling the server for transaction counts in a certain time span and then doing synchronization with the database if the totals don't match?

**Comment by tlipski** [comment]
OK, but the Taxamo transaction in unconfirmed state is not an invoice? Confirmed transaction in Taxamo can issue an invoice if you have this option enabled.

You can treat an unconfirmed transaction as tax calculation log - just like a customer asking for a written offer that they might take or not.

**Comment by bbozo** [comment]
Aaaa :D wow, thank you for the clarification :) that will do for now I think :)

I'll schedule a job in sidekiq to confirm the transaction record on Taxamo some minutes after successful billing, not ideal, but that should negate any double processing, worst case scenario is that a transaction could be updated to completed status twice, which I guess should not be an issue?

**Comment by tlipski** [comment]
Glad I could help :)

If an attempt to confirm an already confirmed transaction is made, an error will be returned (but the transaction will still be confirmed). You can also un-confirm a transaction, unless it has been refunded partially or fully.
