### ISSUE TITLE
Conflict with the 'countries' gem

### ISSUE THREAD

**Issue by WKD** [taxamo/taxamo-ruby#6]
Since the Taxamo classes doesn't use namespaces, it can easily conflict with classes from other gems and/or Rails applications, especially on models using common names (such as Country & Report).

This happens with the "countries" gem (used by country_select and simple_form) : 
https://github.com/hexorx/countries

When you try to use both Taxamo and this gem, you get a loading error.

My opinion is that every class in Taxamo should be prefixed by a Taxamo namespace.

**Comment by tlipski** [comment]
Hi @WKD 

Please try '2.0.1' version from 2.0 brach:

https://github.com/taxamo/taxamo-ruby/tree/2.0

**Comment by WKD** [comment]
Hello,

It indeed worked very well, thanks!

Maybe you should advertise this release on rubygems.org?
