### ISSUE TITLE
models not namespaced

### ISSUE THREAD

**Issue by newton10471** [taxamo/taxamo-ruby#7]
The models aren't namespaced or enclosed inside a module to something like Taxamo::Report, so that the Report model exists in the global namespace.  This means that anyone with a Report model already in their app can't use this gem (without rewriting their own app as namespaced) because the model names clash.  The convention, as I understand it, is to namespace models of gems inside modules, in order to avoid the model name clash issue.

**Comment by tlipski** [comment]
Hi, please try using the 2.0 branch: https://github.com/taxamo/taxamo-ruby/tree/2.0

**Comment by tlipski** [comment]
Updated readme with namespaced version reference, it is also in `master` branch and on RubyGems
